# Generated by Django 5.2.6 on 2025-09-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_quiz_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
