# Generated by Django 5.2.6 on 2025-10-15 05:32

from django.db import migrations, models
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_category_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, related_name='uploaded_notes', to='auth.user'),
            preserve_default=False,
        ),
    ]
