# Generated by Django 5.2.6 on 2025-10-15 06:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20251015_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
