# Generated by Django 5.2.6 on 2025-10-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_note_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
        migrations.AddField(
            model_name='note',
            name='content_html',
            field=models.TextField(default=''),
        ),
    ]
