# Generated by Django 5.2.6 on 2025-10-18 22:01

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_course_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(help_text='Comma-separated list of authors', max_length=500)),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='research_papers/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=200, null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_research_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
