# Generated by Django 5.2.6 on 2025-11-08 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_quizattempt_time_taken_useranswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='upload_type',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Notes', 'Notes'), ('Question Bank', 'Question Bank'), ('Papers', 'Papers')], default='Assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='upload_type',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Notes', 'Notes'), ('Question Bank', 'Question Bank'), ('Papers', 'Papers')], default='Notes', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='myapp.quizattempt'),
        ),
    ]
