# Generated by Django 5.2.6 on 2025-11-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_useranswer_unique_together_assignment_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='year',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pass_out_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
