# Generated by Django 5.2.6 on 2025-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_studentprofile_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
