# Generated by Django 5.2.6 on 2025-11-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_studentprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pass_out_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
