# Generated by Django 5.2.6 on 2025-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pass_out_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
