# Generated by Django 5.2.6 on 2025-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_teacherprofile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.course'),
        ),
    ]
