# Generated by Django 5.2.6 on 2025-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_teacherprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='upload_type',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Notes', 'Notes'), ('Question Bank', 'Question Bank'), ('Papers', 'Papers'), ('Lab Manual', 'Lab Manual'), ('Presentation', 'Presentation'), ('Syllabus', 'Syllabus'), ('Other', 'Other')], default='Notes', max_length=20),
        ),
    ]
