# Generated by Django 5.2.6 on 2025-11-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_note_department_note_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
