# Generated by Django 5.2.6 on 2025-11-09 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_assignment_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('notes', 'Notes'), ('question-bank', 'Question Bank'), ('lab-manual', 'Lab Manual'), ('presentation', 'Presentation'), ('syllabus', 'Syllabus'), ('other', 'Other')], max_length=20)),
                ('department', models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electronics & Electrical Engineering', 'Electronics & Electrical Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Aerospace Engineering', 'Aerospace Engineering'), ('Automobile Engineering', 'Automobile Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Biotechnology', 'Biotechnology'), ('Industrial Engineering', 'Industrial Engineering'), ('Textile Engineering', 'Textile Engineering'), ('Metallurgical Engineering', 'Metallurgical Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Petroleum Engineering', 'Petroleum Engineering'), ('Agricultural Engineering', 'Agricultural Engineering'), ('Production Engineering', 'Production Engineering'), ('Robotics & Automation', 'Robotics & Automation'), ('Mechatronics Engineering', 'Mechatronics Engineering'), ('Marine Engineering', 'Marine Engineering'), ('Instrumentation Engineering', 'Instrumentation Engineering'), ('Environmental Engineering', 'Environmental Engineering'), ('Structural Engineering', 'Structural Engineering'), ('Railway Engineering', 'Railway Engineering'), ('Ceramic Engineering', 'Ceramic Engineering'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Software Engineering', 'Software Engineering'), ('Food Technology', 'Food Technology')], max_length=255)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], max_length=10)),
                ('section', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('D1', 'D1')], max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='teacher_content/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_teacher_content', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
