# Generated by Django 5.2.6 on 2025-11-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_teachersubjectcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjectcontent',
            name='department',
            field=models.CharField(choices=[('Computer Science & Engineering (CSE)', 'Computer Science & Engineering (CSE)'), ('Artificial Intelligence & Data Science (AIDS)', 'Artificial Intelligence & Data Science (AIDS)'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Electronics & Communication Engineering (ECE)', 'Electronics & Communication Engineering (ECE)'), ('Electrical Engineering (EE)', 'Electrical Engineering (EE)'), ('Mechanical Engineering (ME)', 'Mechanical Engineering (ME)'), ('Civil Engineering (CE)', 'Civil Engineering (CE)'), ('Chemical Engineering (CHE)', 'Chemical Engineering (CHE)'), ('Aerospace Engineering (AE)', 'Aerospace Engineering (AE)'), ('Automobile Engineering (AUTO)', 'Automobile Engineering (AUTO)'), ('Biomedical Engineering (BME)', 'Biomedical Engineering (BME)'), ('Instrumentation Engineering (IE)', 'Instrumentation Engineering (IE)'), ('Physics (PHY)', 'Physics (PHY)'), ('Chemistry (CHEM)', 'Chemistry (CHEM)'), ('Mathematics (MATH)', 'Mathematics (MATH)'), ('Computer Science (CS)', 'Computer Science (CS)'), ('Biology (BIO)', 'Biology (BIO)'), ('Business Administration (BBA)', 'Business Administration (BBA)'), ('Master of Business Administration (MBA)', 'Master of Business Administration (MBA)'), ('Finance (FIN)', 'Finance (FIN)'), ('Marketing (MKT)', 'Marketing (MKT)'), ('HR Management (HR)', 'HR Management (HR)'), ('Computer Engineering (CO)', 'Computer Engineering (CO)'), ('Mechanical Engineering (ME)', 'Mechanical Engineering (ME)'), ('Civil Engineering (CE)', 'Civil Engineering (CE)'), ('Electrical Engineering (EE)', 'Electrical Engineering (EE)'), ('Electronics Engineering (EX)', 'Electronics Engineering (EX)')], max_length=255),
        ),
    ]
