# Generated by Django 5.2.6 on 2025-11-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.course'),
        ),
    ]
