# Generated by Django 5.2.6 on 2025-11-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_studentprofile_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectcontent',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_profiles/'),
        ),
        migrations.AddField(
            model_name='teachersubjectcontent',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teachersubjectcontent',
            name='content_type',
            field=models.CharField(choices=[('notes', 'Notes'), ('question-bank', 'Question Bank'), ('lab-manual', 'Lab Manual'), ('presentation', 'Presentation'), ('papers', 'Papers'), ('assignments', 'Assignments'), ('syllabus', 'Syllabus'), ('other', 'Other')], max_length=20),
        ),
    ]
