# Generated by Django 5.2.6 on 2025-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_teachersubjectcontent_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectcontent',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teachersubjectcontent',
            name='submission_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
