from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),

    path('student/semister-content/', views.student_semister_content, name='student_semister_content'),
    path('student/semester-progress/', views.semester_progress, name='semester_progress'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('course/add/', views.add_course, name='add_course'),
    path('category/add/', views.add_category, name='add_category'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('course/<int:course_id>/notes/', views.course_notes, name='course_notes'),
    path('course/<int:course_id>/notes/add/', views.add_note_to_course, name='add_note_to_course'),
    path('note/<int:note_id>/download-pdf/', views.download_note_html_as_pdf, name='download_note_html_as_pdf'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('course/edit/<int:course_id>/', views.edit_course, name='edit_course'),
    path('course/delete/<int:course_id>/', views.delete_course, name='delete_course'),
    path('quiz/add/', views.add_quiz, name='add_quiz'),
    path('quiz/edit/<int:quiz_id>/', views.edit_quiz, name='edit_quiz'),
    path('quiz/delete/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path('question/add/', views.add_question, name='add_question'),
    path('quiz/attempt/<int:quiz_id>/', views.attempt_quiz, name='attempt_quiz'),
    path('quiz/results/', views.view_results, name='view_results'),
    path('scoreboard/', views.scoreboard, name='scoreboard'),

    path('courses/', views.courses, name='courses'),
    path('assignments/', views.assignments, name='assignments'),
    path('assignment/<int:assignment_id>/', views.assignment_detail, name='assignment_detail'),
    path('assignment/add/', views.add_assignment, name='add_assignment'),
    path('assignment/edit/<int:assignment_id>/', views.edit_assignment, name='edit_assignment'),
    path('assignment/delete/<int:assignment_id>/', views.delete_assignment, name='delete_assignment'),
    path('progress/', views.progress, name='progress'),
    path('notes/', views.notes, name='notes'),
    path('note/add/', views.add_note, name='add_note'),
    path('note/edit/<int:note_id>/', views.edit_note, name='edit_note'),
    path('note/delete/<int:note_id>/', views.delete_note, name='delete_note'),
    path('resources/', views.resources, name='resources'),
    path('about/', views.about, name='about'),
    path('research-paper/', views.research_paper, name='research_paper'),
    path('research-paper/add/', views.add_research_paper, name='add_research_paper'),
    path('research-paper/edit/<int:paper_id>/', views.edit_research_paper, name='edit_research_paper'),
    path('research-paper/delete/<int:paper_id>/', views.delete_research_paper, name='delete_research_paper'),
    path('students/', views.student_list, name='student_list'),
    path('all-quiz/', views.all_quiz, name='all_quiz'),

    # Teacher management URLs
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('teacher/create/', views.create_teacher, name='create_teacher'),
    path('teacher/delete/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),
    path('teacher/reset-password/<int:teacher_id>/', views.reset_teacher_password, name='reset_teacher_password'),
    path('teacher/assign-courses/<int:teacher_id>/', views.assign_courses_to_teacher, name='assign_courses_to_teacher'),
    path('teacher/dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('teacher/subject-content/', views.teacher_subject_content, name='teacher_subject_content'),
    path('teacher/content/delete/<int:content_id>/', views.delete_teacher_content, name='delete_teacher_content'),
    path('teacher/content/edit/<int:content_id>/', views.edit_teacher_content, name='edit_teacher_content'),
    path('documents/', views.documents, name='documents'),
    path('documents/set-pin/', views.set_pin, name='set_pin'),
    path('documents/verify-pin/', views.verify_pin, name='verify_pin'),
    path('documents/recovery/', views.recovery, name='recovery'),
    path('documents/reset-data/', views.reset_data, name='reset_data'),
    path('documents/upload-student/', views.upload_student_document, name='upload_student_document'),
    path('documents/upload-teacher/', views.upload_teacher_document, name='upload_teacher_document'),
    path('text_classify/', views.text_classify, name='text_classify'),
    path('predict/', views.predict, name='predict'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<str:token>/', views.reset_password, name='reset_password'),
    path('img-to-text-ocr/', views.img_to_text_ocr, name='img_to_text_ocr'),
    path('available-content/', views.available_content_view, name='available_content'),
    path('vibhavna-ai/', views.vibhavna_ai, name='vibhavna_ai'),
    path('ollama-stream/', views.ollama_stream, name='ollama_stream'),
    path('settings/', views.settings, name='settings'),
]
